[package]
name = "cubist-wallet-provisioner"
version = "0.1.0"
edition = "2021"

[lib]
name = "cubist_wallet_provisioner"
path = "src/lib.rs"

[dependencies]
# cubist-policy-sdk = { path = "./cubist-policy-sdk-main/sdk" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"

