[package]
name = "skate-provisioner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "skate_provisioner"
path = "src/main.rs"

[dependencies]
cubist-policy-sdk = { path = "../cubist-policy-sdk-main/sdk" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
